### ISSUE TITLE
Increase resolution

### ISSUE THREAD

**Issue by Leseratte10** [chinuno-usami/CuteR#10]
Is there a way to make the image quality of the resulting QR code better? I haven't found any size/resolution parameter, and no matter which version I use, the image gets larger with higher version numbers but the quality of the QR code is still pretty bad. 

For example, when I take the microsoft logo (2000x2000px, see [here](https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/2000px-Microsoft_logo.svg.png) )  and turn that into a QR code ...
`python3 ./CuteR.py -o output.png -C -p ms.png microsoft`
this is the result: 
![output](https://user-images.githubusercontent.com/6040787/100441058-22b62980-30a6-11eb-9930-a8aa831224f9.png)

The image has 2000x2000 pixels like the original, but it looks like it's been rendered at something like 80x80 and then upscaled to 2000x2000 again. Why is this so low-quality? 

I looked into the source code and it looks like the QR code is always generated in a fixed size. Why is that the case? The resulting image would be a way higher quality if the QR code size would be set to the image size.

Or am I missing something? Why does my Microsoft QR code look so bad?

**Comment by chinuno-usami** [comment]
Fixed. 
Check latest commit for update.
