### ISSUE TITLE
Change dot size?

### ISSUE THREAD

**Issue by ftrotter** [chinuno-usami/CuteR#7]
This is really cool. 

Is there any way that you could make the size of the white and colored dots as a parameter?

I want to experiment with scannability vs image size, and I think that I might be able to make a smaller image, if there were large 'dots' of data...

In any case, thank you for a great project.

-FT

**Comment by chinuno-usami** [comment]
[AwesomeQRCode](https://github.com/SumiMakito/AwesomeQRCode) and [Awesome-qr.js](https://github.com/SumiMakito/Awesome-qr.js ) of @SumiMakito provide a parameter of `dotScale` would satisfy with your requirement.

**Comment by sumimakito** [comment]
Wow! It seems that I've just found another cute QR code generator. (≧∀≦*)

**Comment by ftrotter** [comment]
Thank you. Again, really cool project!

-FT
