### ISSUE TITLE
gif处理后体积大了67倍´_＞`

### ISSUE THREAD

**Issue by SekiBetu** [chinuno-usami/CuteR#9]
该如何解决

**Comment by chinuno-usami** [comment]
嗯。。大尺寸的gif体积都是很大的
一方面，处理后的图片为了保留细节默认会设置一个比较大的输出尺寸，如果不需要大图片可以resize到需要的大小。
另一方面，输出的gif没有做重复像素优化，有些软件会对gif里面每帧重复的像素做优化，这个实现起来挺麻烦的，效果又不一定有专门的软件好，所以没做这个优化。优化工具网上搜也能搜到挺多的，还有各种在线服务，ps输出gif也会有一定的优化。
如果是放网页上的话可以考虑转成mp4或者webm这样的视频格式播放，体积都是非常小的

XIBIE <notifications@github.com> 於 2019年6月23日 週日 19:51 寫道：

**Comment by SekiBetu** [comment]
用了几个软件比如gifsicle 试着优化，看来只有降低像素才能保证清楚的情况下减少体积，原本300X300的gif做完二维码，缩到180X180才等于原来的体积，看来是世界难题了
